### ISSUE TITLE
generate-changelog fails with permissions issue of file created

### ISSUE THREAD

**Issue by Tylorjg** [liquibase/github-action-generator#65]
When using the generate-changelog action, it fails with the error below. I'm unsure where this file is supposed to be generated if this is successful? In the end, it runs inside a docker container, but are any volumes being mapped back to anywhere. Should it end up in the repo?

```
[2023-03-02 18:28:58] WARNING [liquibase.resource] Failed to create parent directories for file changelogs/test.xml
[463](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:464)
[2023-03-02 18:28:59] SEVERE [liquibase.integration] changelogs/test.xml
[464](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:465)
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.nio.file.AccessDeniedException: changelogs/test.xml
[465](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:466)
	at liquibase.command.CommandScope.execute(CommandScope.java:186)
[466](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:467)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
[467](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:468)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
[468](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:469)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
[469](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:470)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
[470](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:471)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
[471](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:472)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
[472](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:473)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
[473](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:474)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
[474](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:475)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
[475](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:476)
	at picocli.CommandLine.execute(CommandLine.java:2170)
[476](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:477)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:352)
[477](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:478)
	at liquibase.Scope.child(Scope.java:189)
[478](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:479)
	at liquibase.Scope.child(Scope.java:165)
[479](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:480)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:317)
[480](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:481)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:84)
[481](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:482)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[482](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:483)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[483](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:484)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[484](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:485)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[485](https://github.com/Tylorjg/tylor_github_actions/actions/runs/4317087012/jobs/7533711874#step:4:486)
	at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
```

**Comment by ragchuck** [comment]
I have a similar issue but with the snapshot and execute-sql in. I use the `outputFile` parameter to specify the filename, but the github-action fails to execute.

```
[2023-07-13 12:53:33] INFO [liquibase.integration] Starting command execution.
[2023-07-13 12:53:33] FINE [liquibase.configuration] Found 'liquibase.outputFile' configuration of 'badm-postgres-pk_business.json'
    command argument '--output-file' of 'badm-postgres-pk_business.json'
[2023-07-13 12:53:33] SEVERE [liquibase.integration] badm-postgres-pk_business.json
java.nio.file.AccessDeniedException: badm-postgres-pk_business.json
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
	at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
	at liquibase.resource.DirectoryPathHandler.createResource(DirectoryPathHandler.java:52)
	at liquibase.resource.PathHandlerFactory.createResource(PathHandlerFactory.java:52)
	at liquibase.resource.PathHandlerFactory.openResourceOutputStream(PathHandlerFactory.java:95)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$2(LiquibaseCommandLine.java:381)
	at liquibase.Scope.child(Scope.java:206)
	at liquibase.Scope.child(Scope.java:182)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:356)
	at liquibase.Scope.child(Scope.java:206)
	at liquibase.Scope.child(Scope.java:182)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:354)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:[94](https://atc-github.azure.cloud.bmw/q447823/badm-master/runs/3973955?check_suite_focus=true#step:8:95))
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:[107](https://atc-github.azure.cloud.bmw/q447823/badm-master/runs/3973955?check_suite_focus=true#step:8:108))
```

same issue when providing path like /github/workspace, where the workspace is mounted....

**Comment by ragchuck** [comment]
after fiddling around I came up with a temporary directory that is created with `-m777`, where I can point the outputFile parameter, then liquibase can write the files.

Github Actions don't recommend to overwrite the default root user as explained here: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#docker-container-filesystem
But the liquibase container runs with the 'liquibase' user, as defined here: https://github.com/liquibase/docker/blob/main/Dockerfile#L46

**Comment by jnewton03** [comment]
@Tylorjg there have been a number of fixes to the underlying docker container.  Can you see if this is still an issue?  If so, please open a new ticket with steps to reproduce.  Thank You!
